variables:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - group: Stable
  - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - group: Non-Stable

jobs:
  - job: ci
    displayName: 'CI'
    pool:
      vmImage: 'windows-latest'
    variables:
      pullRequestNumber: $[coalesce(variables['System.PullRequest.PullRequestNumber'], '')]
      buildNumber: $[counter('X', 1)]
    steps:
      - task: PowerShell@2
        displayName: 'Run build.ps1'
        env:
          NUGET_API_KEY: $(NuGetApiKey)
          GITHUB_PAT: $(GitHubPat)
        inputs:
          targetType: 'filePath'
          filepath: $(System.DefaultWorkingDirectory)\build.ps1
          pwsh: true
          arguments: >
            -Target $(Cake.Target)
            -Verbosity $(Cake.Verbosity)
            --configuration=$(Configuration)
            --build-number=$(buildNumber)
            --pr-number=$(pullRequestNumber)
            --nuget-feed=$(NuGetFeed)
            --nuget-user-name=$(NuGetUserName)
            --nuget-api-key=$env:NUGET_API_KEY
            --github-repo-name=$(Build.Repository.Name)
            --github-repo-owner=$(GitHubRepositoryOwner)
            --github-pat=$env:GITHUB_PAT
